using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace GameDatabase.GameDatabase.Helpers
{
    [AttributeUsage(AttributeTargets.Field,AllowMultiple = true)]
    public class AutoCompleteAtribute : Attribute
    {


        public AutoCompleteAtribute(Type type)
        {
            this.type = type;
        }

        public bool AddImages()
        {
            switch (type)
            {
                case Type.Controls:
                case Type.ComponentIcon:
                case Type.ShipIcon:
                case Type.ShipSprite:
                case Type.Image:
                case Type.EffectSprite:
                case Type.BulletSprite:
                case Type.AvatarSprite:
                case Type.ArtifactSprite:
                    return true;
            }
            return false;
        }

        public string[] getCompletion()
        {

            switch (type)
            {
                case Type.SoundObsolete:
                    return new string[]
                    {
                        "01. Light Latt",
                        "alarm",
                        "alarm2",
                        "buy",
                        "engine",
                        "explosion_01",
                        "explosion_02",
                        "explosion_03",
                        "explosion_04",
                        "explosion_05",
                        "explosion_06",
                        "explosion_08",
                        "explosion_09",
                        "explosion_10",
                        "flux_01",
                        "flux_02",
                        "flux_03",
                        "flux_04",
                        "flux_05",
                        "flux_06",
                        "hit_01",
                        "hit_02",
                        "hit_03",
                        "hit_04",
                        "hit_05",
                        "hit_06",
                        "hit_07",
                        "hit_08",
                        "hit_09",
                        "hit_10",
                        "hit_11",
                        "launch_01",
                        "launch_02",
                        "launch_03",
                        "launch_04",
                        "launch_05",
                        "launch_06",
                        "launch_07",
                        "launch_08",
                        "launch_09",
                        "repair",
                        "scrap",
                        "shot_01",
                        "shot_02",
                        "shot_03",
                        "shot_04",
                        "shot_05",
                        "shot_06",
                        "shot_07",
                        "shot_08",
                        "shot_09",
                        "shot_10",
                        "shot_11",
                        "shot_12",
                        "shot_13",
                        "shot_14",
                        "shot_15",
                        "SynthR - Battalion",
                        "SynthR - Launch Detected",
                        "SynthR - The Last Prophecy (2011 Reconstruction)",
                        "With love from Vertex Studio (3)"
                    };
                case Type.Controls:
                    return new string[]
                    {
                        "controls_arrow",
                        "controls_boost",
                        "controls_drone",
                        "controls_gear",
                        "controls_ghost",
                        "controls_joystick",
                        "controls_laser",
                        "controls_mine",
                        "controls_missile",
                        "controls_repair",
                        "controls_selfdestruct",
                        "controls_shield",
                        "controls_shock",
                        "controls_shot",
                        "controls_web"
                    };
                case Type.ComponentIcon:
                    return new string[]
                    {
                        "accelerator1",
                        "afterburner1",
                        "armor11",
                        "armor12",
                        "armor13",
                        "armor21",
                        "armor22",
                        "armor23",
                        "armor31",
                        "armor32",
                        "armor33",
                        "armor41",
                        "armor42",
                        "armor43",
                        "armor51",
                        "armor52",
                        "armor53",
                        "ArmoredTank1",
                        "ArmoredTank2",
                        "block",
                        "detonator1",
                        "doom1",
                        "drone_power1",
                        "drone_power2",
                        "drone_power3",
                        "drone_replicator1",
                        "drone_replicator2",
                        "drone_replicator3",
                        "dronebay1",
                        "dronebay2",
                        "dronebay3",
                        "DroneDamage",
                        "DroneRange",
                        "energybeam1",
                        "energybeam2",
                        "engine0",
                        "engine1",
                        "engine2",
                        "engine3",
                        "engine4",
                        "engine5",
                        "firework",
                        "flamethrower1",
                        "focus1",
                        "focus2",
                        "fueltank11",
                        "fueltank12",
                        "fueltank13",
                        "fueltank21",
                        "fueltank22",
                        "fueltank23",
                        "gun1",
                        "gun2",
                        "gun3",
                        "gun4",
                        "gun5",
                        "gun6",
                        "gun7",
                        "hangar",
                        "holy_gun",
                        "inertial1",
                        "inertial2",
                        "intertial_damper1",
                        "intertial_damper2",
                        "ion_cannon1",
                        "ion_cannon2",
                        "jammer",
                        "laser1",
                        "laser2",
                        "laser3",
                        "laser4",
                        "lightweight1",
                        "missile0",
                        "missile1",
                        "missile2",
                        "missile3",
                        "pointdefense",
                        "range1",
                        "reactor1",
                        "reactor2",
                        "reactor21",
                        "reactor22",
                        "reactor3",
                        "RepairBay",
                        "repairbot1",
                        "repairbot2",
                        "rocket1",
                        "shield1",
                        "shield2",
                        "shield_capacitor1",
                        "shield_capacitor2",
                        "shield_capacitor3",
                        "shield_generator1",
                        "shield_generator2",
                        "shield_generator3",
                        "shock1",
                        "shock2",
                        "shotgun1",
                        "shotgun2",
                        "TargetingUnit",
                        "teleporter",
                        "teleporter1",
                        "torpedo1",
                        "torpedo2",
                        "torpedo3",
                        "torpedo4",
                    };
                case Type.ShipIcon:
                    return new string[]
                    {
                        "antipiracy",
                        "f0s1",
                        "f0s1_2",
                        "f0s2",
                        "f0s3",
                        "f0s4",
                        "f12s1",
                        "f13s1",
                        "f13s2",
                        "f13s3",
                        "f13s4",
                        "f1s1",
                        "f1s1_2",
                        "f1s2",
                        "f1s3",
                        "f1s4",
                        "f1s5",
                        "f2s1",
                        "f2s1_2",
                        "f2s2",
                        "f2s3",
                        "f2s4",
                        "f2s5",
                        "f3s1",
                        "f3s1_2",
                        "f3s2",
                        "f3s3",
                        "f3s4",
                        "f4s1",
                        "f4s1_2",
                        "f4s2",
                        "f4s3",
                        "f4s4",
                        "f5s1",
                        "f5s1_2",
                        "f5s2",
                        "f5s3",
                        "f5s4",
                        "f6s1",
                        "f6s1_2",
                        "f6s2",
                        "f6s3",
                        "f6s4",
                        "f6s5",
                        "f7s1",
                        "f7s1_2",
                        "f7s2",
                        "f7s3",
                        "f7s4",
                        "f8s1",
                        "f8s2",
                        "f8s3",
                        "f8s4",
                        "f9s1",
                        "f9s2",
                        "f9s3",
                        "f9s4",
                        "f9s5",
                        "fas1",
                        "fas1_2",
                        "fas2",
                        "fas3",
                        "fas4",
                        "flagship0",
                        "flagship1",
                        "flagship13",
                        "flagship2",
                        "flagship3",
                        "flagship4",
                        "flagship5",
                        "flagship6",
                        "flagship7",
                        "flagship8",
                        "flagship9",
                        "flagshipa",
                        "flagshipn",
                        "flagships",
                        "fns1",
                        "fns10",
                        "fns2",
                        "fns3",
                        "fns4",
                        "fns5",
                        "fns6",
                        "fns7",
                        "fns8",
                        "fns9",
                        "fs1",
                        "fs2",
                        "fs3",
                        "merchant",
                        "unknown_ship",
                        "worm_head",
                        "worm_head2"
                    };
                case Type.ShipSprite:
                    return new string[]
                    {
                        "drone1",
                        "drone2",
                        "drone3",
                        "drone4",
                        "drone5",
                        "drone8",
                        "dronea",
                        "f0s1",
                        "f0s1_2",
                        "f0s2",
                        "f0s3",
                        "f0s4",
                        "f12s1",
                        "f13s1",
                        "f13s2",
                        "f13s3",
                        "f13s4",
                        "f14s1",
                        "f1s1",
                        "f1s1_2",
                        "f1s2",
                        "f1s3",
                        "f1s4",
                        "f1s5",
                        "f2s1",
                        "f2s1_2",
                        "f2s2",
                        "f2s3",
                        "f2s4",
                        "f2s5",
                        "f3s1",
                        "f3s1_2",
                        "f3s2",
                        "f3s3",
                        "f3s4",
                        "f4s1",
                        "f4s1_2",
                        "f4s2",
                        "f4s3",
                        "f4s4",
                        "f5s1",
                        "f5s1_2",
                        "f5s2",
                        "f5s3",
                        "f5s4",
                        "f6s1",
                        "f6s1_2",
                        "f6s2",
                        "f6s3",
                        "f6s4",
                        "f6s5",
                        "f7s1",
                        "f7s1_2",
                        "f7s2",
                        "f7s3",
                        "f7s4",
                        "f8s1",
                        "f8s2",
                        "f8s3",
                        "f8s4",
                        "f9s1",
                        "f9s2",
                        "f9s3",
                        "f9s4",
                        "f9s5",
                        "fas1",
                        "fas1_2",
                        "fas2",
                        "fas3",
                        "fas4",
                        "flagship0",
                        "flagship1",
                        "flagship13",
                        "flagship2",
                        "flagship3",
                        "flagship4",
                        "flagship5",
                        "flagship6",
                        "flagship7",
                        "flagship8",
                        "flagship9",
                        "flagshipa",
                        "flagshipn",
                        "flagships",
                        "fns1",
                        "fns10",
                        "fns1_2",
                        "fns2",
                        "fns3",
                        "fns4",
                        "fns5",
                        "fns6",
                        "fns7",
                        "fns8",
                        "fns9",
                        "fs1",
                        "fs2",
                        "fs3",
                        "merchant",
                        "mothership",
                        "salvage_drone",
                        "santa",
                        "santa_drone",
                        "smuggler",
                        "space_invader",
                        "starbase",
                        "worm_head",
                        "worm_head2"
                    };
                case Type.SateliteSprite:
                    return new string[]
                    {
                        "holy_gun",
                        "hovertank",
                        "hovertank_gun",
                        "repair_bot",
                        "santa_gun",
                        "satellite1",
                        "satellite2",
                        "satellite3",
                        "satellite4",
                        "satellite5",
                        "satellite6",
                        "satellite7",
                        "scavenger_arm",
                        "turret",
                        "worm_joint",
                        "worm_joint2",
                        "worm_segment",
                        "worm_segment2"
                    };
                case Type.EffectSprite:
                    return new string[]
                    {
                        "cloud",
                        "CloudWhite",
                        "engine_light",
                        "EngineTrail",
                        "shield",
                        "star",
                        "wave"
                    };
                case Type.BulletSprite:
                    return new string[]
                    {
                        "bomb",
                        "energy1",
                        "fragment",
                        "hotspot1",
                        "laser",
                        "laser_beam",
                        "mine",
                        "plasma",
                        "plasma2",
                        "rocket",
                        "rocket2",
                        "star",
                        "tutorial_bullet",
                        "twister",
                        "vortex"
                    };
                case Type.AvatarSprite:
                    return new string[]
                    {
                        "A_12",
                        "K_07",
                        "M_07",
                        "M_12",
                        "M_16"
                    };
                case Type.ArtifactSprite:
                    return new string[]
                    {
                        "artifact",
                        "eye",
                        "scull",
                        "snowflake",
                        "stone",
                        "tubes"
                    };
                default:
                    return new string[0];
            }
        }
        
        public AutoCompleteAtribute.Type type;

        public enum Type
        {
            None,
            SoundObsolete,
            Controls,
            ComponentIcon,
            ShipIcon,
            ShipSprite,
            SateliteSprite,
            EffectSprite,
            BulletSprite,
            AvatarSprite,
            ArtifactSprite,
            Image,
        }
    }
}
